version: "3.9"

services:
  nipdb:
    image: "mariadb:10.7"
    restart: 'always'
    volumes:
      - nip_data:/var/lib/mysql
    environment:
      MARIADB_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD}
      MARIADB_DATABASE: ${NIP5_DATABASE_NAME}
      MARIADB_USER: ${NIP5_DATABASE_USER}
      MARIADB_PASSWORD: ${NIP5_DATABASE_PASS}

  nip5server:
    image: "nip5server:latest"
    restart: 'always'
    ports:
      - "${NIP5_SERVER_PORT}:8080"
    depends_on:
      - nipdb
    links:
      - nipdb
    environment:
      LOGGING_LEVEL_DE_FEIKE: INFO
      NIP5_DATABASE_URL: ${NIP5_DATABASE_URL}
      NIP5_DATABASE_USER: ${NIP5_DATABASE_USER}
      NIP5_DATABASE_PASS: ${NIP5_DATABASE_PASS}
      NIP5_ADMIN_SECRET: ${NIP5_ADMIN_SECRET}

volumes:
  nip_data:
